export const items = [
        {
            src: "public/DarkGray.jpg",
            city: "North Melborune",
            areaCode: "NMLO1",
            desc1: "Net Income",
            netIncome: "$360,000",
            desc2: "Net Yield",
            netTield: "6.4%",
            id: 1,
        },
        {
            src: "public/Lovely Archi.jpg",
            city: "Frankston Orca",
            areaCode: "ARNO1",
            desc1: "Net Income",
            netIncome: "$240,000",
            desc2: "Net Yield",
            netTield: "5.3%",
            id: 2,
        },
        {
            src: "public/Gray .jpg",
            city: "Potts Points Carnige",
            areaCode: "CNG01",
            desc1: "Net Income",
            netIncome: "$320,000",
            desc2: "Net Yield",
            netTield: "6.4%",
            id: 3,
        },
        {
            src: "public/With flowers.jpg",
            city: "Kreuzberg, Berlin",
            areaCode: "BLN01",
            desc1: "Net Income",
            netIncome: "$240,000",
            desc2: "Net Yield",
            netTield: "5.3%",
            id: 4,
        },
    ];