export const items = [
        {
            src: "/DarkGray.jpg",
            city: "North Melborune",
            areaCode: "NMLO1",
            desc1: "Net Income",
            netIncome: "$360,000",
            desc2: "Net Yield",
            netTield: "6.4%",
            id: 1,
        },
        {
            src: "/Lovely Archi.jpg",
            city: "Frankston Orca",
            areaCode: "ARNO1",
            desc1: "Net Income",
            netIncome: "$240,000",
            desc2: "Net Yield",
            netTield: "5.3%",
            id: 2,
        },
        {
            src: "/Gray .jpg",
            city: "Potts Points Carnige",
            areaCode: "CNG01",
            desc1: "Net Income",
            netIncome: "$320,000",
            desc2: "Net Yield",
            netTield: "6.4%",
            id: 3,
        },
        {
            src: "/newWhite.jpg",
            city: "Kreuzberg, Berlin",
            areaCode: "BLN01",
            desc1: "Net Income",
            netIncome: "$240,000",
            desc2: "Net Yield",
            netTield: "5.3%",
            id: 4,
        },
        {
            src: "/Gated.jpg",
            city: "Keong Saik, Singapore",
            areaCode: "SGP01",
            desc1: "Net Income",
            netIncome: "$360,000",
            desc2: "Net Yield",
            netTield: "6.6%",
            id: 5,
        },
        {
            src: "/Block.jpg",
            city: "Wicker Park, Chicago",
            areaCode: "CHI01",
            desc1: "Net Income",
            netIncome: "$240,000",
            desc2: "Net Yield",
            netTield: "5.3%",
            id: 6,
        },
];
    
export const testimonials = [
    {
        name: "Patrick Mahomes",
        location: "New York, USA",
        picture: "/Patrick.jpg",
        rating: "5/5 ⭐⭐⭐⭐⭐",
        text: "I had a fantastic experience working with IntelliVest. Their expertise and guidance helped me make informed decisions, and I'm extremely satisfied with the results.",
    },
    {
        name: "Alice Smith",
        location: "London, UK",
        picture: "/Alice.jpg",
        rating: "4/5 ⭐⭐⭐⭐",
        text: "As someone new to property investment, I appreciate the personalized advice and transparent communication provided by Intellivest. It made the entire process smooth and hassle-free.",
    },
    {
        name: "Robert Murdoch",
        location: "Sydney, Australia",
        picture: "/Robert.jpg",
        rating: "5/5 ⭐⭐⭐⭐⭐",
        text: "The team at this property investment company demonstrated a deep understanding of market trends. Their strategies proved to be effective, and I've seen significant returns on my investments.",
    },
];
